name = "AoC"
testRunner = "Benchmark"
defaultTargets = ["aoc"]

[[require]]
name = "batteries"
git = "https://github.com/leanprover-community/batteries"
rev = "main"

[[require]]
name = "aesop"
git = "https://github.com/leanprover-community/aesop"
rev = "master"

[[lean_lib]]
name = "AoC"

[[lean_exe]]
name = "aoc"
root = "Main"

[[lean_exe]]
name = "Benchmark"
root = "Benchmark"
