name = "AoC"
testRunner = "Benchmark"
defaultTargets = ["aoc"]
version = "0.1.0"

[[require]]
name = "aesop"
scope = "leanprover-community"

[[require]]
name = "batteries"
scope = "leanprover-community"

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "AoC"

[[lean_lib]]
name = "Y2023"

[[lean_lib]]
name = "Y2024"

[[lean_exe]]
name = "aoc"
root = "AoC"

[[lean_exe]]
name = "Benchmark"
root = "Benchmark"
