name = "AoC"
testRunner = "Benchmark"
defaultTargets = ["aoc"]

[[require]]
name = "batteries"
scope = "leanprover-community"

[[require]]
name = "aesop"
scope = "leanprover-community"

[[lean_lib]]
name = "AoC"

[[lean_exe]]
name = "aoc"
root = "Main"

[[lean_exe]]
name = "Benchmark"
root = "Benchmark"
