name = "AoC"
version = "0.6.1"
lintDriver = "batteries/runLinter"
testRunner = "testDriver"
defaultTargets = ["aoc"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
linter.missingDocs = false
linter.unusedVariables = true

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "v4.35.0-rc2"

[[require]]
name = "Cli"
scope = "leanprover"
git = "git@github.com:leanprover/lean4-cli.git"
rev = "v4.35.0-rc2"

[[require]]
name = "lean4-itertools"
scope = "shnarazk"
git = "git@github.com:shnarazk/lean4-itertools.git"
rev = "main"

[[require]]
name = "lean4-winnow"
scope = "shnarazk"
git = "git@github.com:shnarazk/lean4-winnow.git"
rev = "main"

[[lean_lib]]
name = "AoC"

[[lean_lib]]
name = "Y2023"

[[lean_lib]]
name = "Y2024"

[[lean_lib]]
name = "Y2025"

[[lean_exe]]
name = "aoc"
root = "AoC"
moreLinkArgs = ["-O3", "-UNDEBUG"]
buildType = "release"

[[lean_exe]]
name = "testDriver"
# globs = [".+"]
root = "testDriver"
srcDir = "tests"
